name: flutter_di_showcase
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  loading_overlay: ^0.3.0
  path: ^1.7.0
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/env/
